# Use Node.js as the base image
FROM node:22.9.0 AS build

# Set the working directory
WORKDIR /lcimsapp

# Copy dependency definitions
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's source code (including tsconfig.*.json, src/, etc.)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]