
# Node.js v22.9.0 as the base image for the build

FROM node:22.9.0 AS build

# Set the working directory to /lcimsapp in the container
WORKDIR /lcimsapp


# Copy package.json, package-lock.json, and tsconfig.json
COPY package*.json ./
COPY tsconfig.json ./


# Install the dependencies from package.json
RUN npm install
RUN npm run build


# Copy the rest of the application files to the working directory
COPY . .

# Serve the app using a lightweight webserver
FROM nginx:stable-alpine

# Copy the built files from the previous stage to the NGINX server directory
COPY --from=build /lcimsapp/dist /usr/share/nginx/html

# Expose port 80 for the web server
EXPOSE 8000

# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]


